title: 'Resume | Sangam Kumar (sangamcse)'
description: 'Thank you for visiting my resume webpage'
email: 'meetsangamcse@gmail.com'

mainsite: 'www.sangam.dev'

resume_pdf: '/latex/SANGAM_KUMAR.pdf'

username:
  twitter: meetsangamcse
  github: sangamcse
  linkedin: sangamcse

education: true
profile: false
experience: true
volunteer: true
skills: true
projects: true
awards: true
interests: true

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

analytics: UA-118439543-2

exclude:
  [
    'latex/main.tex',
    'latex/res.cls',
    'latex/certificate/',
    'latex/src/',
    'README.md',
    'Gemfile',
    'Gemfile.lock',
  ]
